# Generated by Django 6.0 on 2026-09-03 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("week_start", models.DateField()),
                ("opens_at", models.DateTimeField(auto_now_add=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("COLLECTING", "Collecting"), ("CLOSED", "Closed")],
                        default="COLLECTING",
                        max_length=20,
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facilitated_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "COLLECTING")),
                        fields=("project",),
                        name="one_collecting_cycle_per_project",
                    )
                ],
            },
        ),
    ]
